### ISSUE TITLE
There may be a timestamping problem

### ISSUE THREAD

**Issue by matlink** [bluezio/ipwebcam-gst#13]
Hi again,
I got this warning when I launch the bash script : 

AVERTISSEMENT : de l'élément /GstPipeline:pipeline0/GstV4l2Sink:v4l2sink0 : De nombreux tampons sont éliminés.
Information de débogage supplémentaire :
gstbasesink.c(2875): gst_base_sink_is_too_late (): /GstPipeline:pipeline0/GstV4l2Sink:v4l2sink0:
There may be a timestamping problem, or this computer is too slow.

Thanks,
Matlink

**Comment by SkippyleGrandGourou** [comment]
FWIW, setting sync=false instead of the default sync=true in prepare-videochat.sh does help.

**Comment by bluezio** [comment]
sync=true seems to have been introduced here, as part of the microphone bridge:

https://github.com/bluezio/ipwebcam-gst/commit/8fecf681ea9c68ba1e4a97a90e85a0d850f3f9ae

With set sync=false, I guess that you could end up with video/audio out of sync? Seems a bit unsafe to leave sync=false by default.

**Comment by SkippyleGrandGourou** [comment]
Probably indeed.  My point wasn't to make it default (I guess if sync=true is explicitly set there's a reason), but to provide a workaround for fixing the gst_base_sink_is_too_late error, which is worst than a desync since it actually results in a freeze (at least in my case).  The sync=false setting may not be a perfect solution but it's good to know, especially for users who don't need audio.

**Comment by bluezio** [comment]
That makes sense. I have added in 8dcddc871e50768c78f5316aa2b4a000322448e4 a SYNC configuration variable with some documentation in line with your comments. I hope it will be useful to future users :-).

**Comment by SkippyleGrandGourou** [comment]
Great, thanks for your work !
